### PR TITLE
Wrap column when looking for innerSelectColumns

### LINKED ISSUE #21: Using aliased columns does not work
When using alias for columns on the select and ordering by them, the package fails to include the aliased column into the first query. 

The issue comes from the column name being wrapped when [collecting the orders](https://github.com/hammerstonedev/fast-paginate/blob/v0.1.6/src/BuilderMixin.php#L38) but [not wrapping it when comparing](https://github.com/hammerstonedev/fast-paginate/blob/v0.1.6/src/BuilderMixin.php#L48) with the actual columns from the select.

A code example where this fails, on a database with an `articles` table, a `categories` table, and an `article_category` pivot table to store the relationships between Article and Category would be:

```php
$articlesQuery = Article::select('articles.*')
    ->join('article_category', 'article_category.article_id', '=', 'articles.id')
    ->where('article_category.category_id', 1);

// Use the article_category column instead to speed up things
$column = 'article_category.article_id';
$columnAlias = 'category_article_id';
$articlesQuery->addSelect("$column as $columnAlias");
$articlesQuery->reorder($columnAlias, 'desc');

$articlesQuery->fastPaginate();
```

The above code throws the following exception:
```
Illuminate\Database\QueryException with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'category_article_id' in 'order clause' (SQL: select `articles`.`id` from `articles` inner join `article_category` on `article_category`.`article_id` = `articles`.`id` where `article_category`.`category_id` = 1 order by `category_article_id` desc limit 15 offset 0)'
```

I'm submitting a MR to fix it which should be #22.

### PR DESCRIPTION
**Pull request by j3j5**
This fixes #21

### CODE REVIEW

**Comment by aarondfrancis** [comment]
@j3j5 lovely, thank you so much! Could you add a test to make sure I never undo this 🙈

**Comment by j3j5** [comment]
:thinking: Interesting, apparently this breaks the count. Let me give it another go later to see why this breaks but it doesn't take the other column. I'll try to add an extra test for this.

**Comment by j3j5** [comment]
Ok, found the issue, I started by wrapping the column name on the `str_contains` function but actually, when the column is an instance of the Expression class, the call to `getValue()` returns a string tha is already wrapped, so it needed to be above. I've added a few tests but please, review them to make sure I didn't mess up anything on there. 

One more thing, I saw that the github actions did not include PHP 8.1, is there a reason? I run all the tests on PHP 8.1

**Comment by aarondfrancis** [comment]
Wonderful job! And thank you for writing all of those tests, that's extremely helpful. 

> One more thing, I saw that the github actions did not include PHP 8.1, is there a reason? I run all the tests on PHP 8.1

Nope, just an oversight. Will add it!

**Comment by j3j5** [comment]
Awesome! Glad to be of help!

**Pull request merged**
