### PR TITLE
Fix union query issue

### PR DESCRIPTION
**Pull request by atapatel**
Resolved an issue with the union query that was causing incorrect results to be returned.

### CODE REVIEW

**Comment by atapatel** [comment]
hey @aarondfrancis I have created this PR for using default pagination method instead of fastPaginate for union query.

**Comment by aarondfrancis** [comment]
Looks great, thank you so much! 🤝

**Comment by atapatel** [comment]
@aarondfrancis my pleasure. I really loved your content on planetsql mysql. 🙏🏻🙏🏻🙏🏻

**Comment by aarondfrancis** [comment]
@atapatel So glad you're enjoying it!

**Pull request merged**
