### PR TITLE
Add missing imports - discovered by PHPStan

### PR DESCRIPTION
**Pull request by szepeviktor**
and fix `@var` tags

@aarondfrancis please consider performing static analysis.

### CODE REVIEW

**Comment by aarondfrancis** [comment]
Can you drop the larastan requirement? I'll merge after that. Thanks!

**Comment by szepeviktor** [comment]
> Can you drop the larastan requirement?

Yes I can. It makes me stop contributing to this project.

**Comment by szepeviktor** [comment]
Done.

**Comment by aarondfrancis** [comment]
Thanks for your contributions. 

I must say that your comments are not very kind, you might consider modifying that in the future.

**Comment by aarondfrancis** [comment]
Published v0.1.1 with the fix!

**Comment by szepeviktor** [comment]
> I must say that your comments are not very kind

Thank you for your feedback!!

How should I phrase _It makes me stop contributing to this project_ ?

**Comment by aarondfrancis** [comment]
Thanks for asking! 

It was more the "Done. Goodbye 👋" that felt rude. You've already edited that out so you probably knew 😄 

I understand written communication is sometimes missing nuance, which makes it tough!

**Pull request merged**
