### PR TITLE
Laravel 11.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 11.x.

**Before merging**, you need to:

- Checkout the `l11-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: Shift detected GitHub Actions which run jobs using a version `matrix`. Shift attempted to [update your configuration](https://github.com/hammerstonedev/fast-paginate/pull/58/commits/63df9ae3dc31ac78c147b107637713897863c5f1?w=1) for Laravel 11. However, you should review these changes to ensure the desired combination of versions are built for your package.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/fast-paginate.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "hammerstone/fast-paginate": "dev-l11-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by scajal** [comment]
Any news on this?

**Comment by irsyadadl** [comment]
Hello, is there any updates @aarondfrancis  ?

**Comment by riskihajar** [comment]
everyone waiting 🕚

**Comment by irsyadadl** [comment]
Maybe we just uninstall this, and use regular laravel pagination. At least until this package support L11.

**Comment by jbraband** [comment]
The replies here are on the verge of becoming content!

**Review by sb-nour — APPROVED** [review]

**Comment by drhoussem** [comment]
Any updates?

**Comment by scajal** [comment]
I personally decided to stop using the package in the projects where it was being used, at least until this is merged.

**Review by aarondfrancis — APPROVED** [review]

**Comment by aarondfrancis** [comment]
Thanks for your patience! Merged. Gonna try to look at the other PRs real quick before tagging a new version.

**Pull request merged**
