### PR TITLE
Fix copy-pasta in BuilderMixin

### PR DESCRIPTION
**Pull request by szepeviktor**
@aarondfrancis It was possible to discover this by performing static analysis.

### CODE REVIEW

**Comment by aarondfrancis** [comment]
I did that on purpose, actually 😄 

That argument is useless because we're passing an explicit page in as the last param.

**Comment by szepeviktor** [comment]
The framework accepts a string in `$pageName`.
What should we do?

**Comment by szepeviktor** [comment]
Could we put in the default value of `"page"`?

**Comment by aarondfrancis** [comment]
It doesn't really matter since it's short-circuited anyway, so we'll just pass it in!

**Comment by aarondfrancis** [comment]
Thanks for the PR!

**Comment by szepeviktor** [comment]
You're welcome.

**Pull request merged**
