### PR TITLE
Solved issue for orderByRaw functions.

### PR DESCRIPTION
**Pull request by atapatel**
I solved this issue https://github.com/hammerstonedev/fast-paginate/pull/35.

### CODE REVIEW

**Comment by atapatel** [comment]
@aarondfrancis did you check this PR?

**Comment by aarondfrancis** [comment]
Yes, I did. I'll ask again over here: what is the _issue_? 

I added a test to `main` and it didn't fail. So what is the failing test or use case?

**Comment by atapatel** [comment]
Give me 10 minute.

**Comment by atapatel** [comment]
image
php version is 8.1.18 
laravel version is  9.52.6

**Comment by atapatel** [comment]
@aarondfrancis does the above snippet helpful?

**Comment by atapatel** [comment]
@aarondfrancis I have merged your PR in my local repository and run the test, and all the tests are passed. but when I use laravel, it gives me above mentioned deprecated error.

**Comment by aarondfrancis** [comment]
Merged #35 instead.

If you can produce a test case that requires this PR vs the one that just filters out the raw orders, I'll reopen this. Thanks for your help!

**Pull request closed without merging**
