### PR TITLE
withCount() and an orderByDesc() results in a column not found exception

### LINKED ISSUE #14: withCount() and an orderByDesc() results in a column not found exception (MySQL)
I've got the following query:

```
$products = Product::query()
     ->withCount('orders')
    ->orderByDesc('orders_count')
    ->fastPaginate();
```

When using fastPaginate(), I get an error with MySQL that the column "orders_count" does not exist. However, when using the standard paginate(), the query works perfectly.

Is there a way I can get this to work using fastPaginate? In my specific situation, I'm attempting to get the most purchased store products hence the count and sort.

Thanks!

### PR DESCRIPTION
**Pull request by realslimsutton**
Fixes #14

### CODE REVIEW

**Comment by realslimsutton** [comment]
I'm still investigating the repurcussions of using `->reorder()` as that'll remove all ordering, not just withCount columns.

I'll also add tests, but currently all tests are failing as I don't have the databases setup.

**Comment by realslimsutton** [comment]
Now that tests are running, I can confirm `->reorder()` definitely is not okay, as expected it removes ordering for all columns (including "non-count" columns). I'm looking for alternatives.

**Comment by realslimsutton** [comment]
My first solution wasn't going to work due to the above issue.

This solution will prevent the sub query from selecting all columns, but also propagate selecting specific columns.
This fixes #14, and maybe even adds support for the "having" clause (although I haven't tested the latter and have left it being deferred).

**Comment by aarondfrancis** [comment]
@realslimsutton I appreciate you putting this together! I think we want to be a little more delicate about how we include subselects, as they can be quite expensive. 

Can you check on #16 and let me know what you think?

**Comment by realslimsutton** [comment]
> @realslimsutton I appreciate you putting this together! I think we want to be a little more delicate about how we include subselects, as they can be quite expensive.
> 
> Can you check on #16 and let me know what you think?

@aarondfrancis I can confirm #16 also fixes the error I was getting, and also returns an ordered collection as expected. Thanks!

**Comment by aarondfrancis** [comment]
Merged #16, closing this now. Thanks again for getting me started here!

**Pull request closed without merging**
